// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXLinqPadForVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXLinqPadForVS.4DC7AA40-674B-4790-A49E-AB7BC541A12A";
        public const string Name = "VSIXLinqPadForVS";
        public const string Description = @"Using LinqPad inside of Visual Studio ToolWindow to run linq queries.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Danny McNaught";
        public const string Tags = "";
    }
}
