// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXLinqPadForVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXLinqPadForVS.63e06039-0f82-42ab-a4b9-a44c88ece194";
        public const string Name = "VSIXLinqPadForVS";
        public const string Description = @"Using LinqPad inside of Visual Studio ToolWindow to run linq queries.";
        public const string Language = "en-US";
        public const string Version = "1.10";
        public const string Author = "Danny McNaught";
        public const string Tags = "";
    }
}
