// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXLinqPadForVS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorFactoryString = "7f7100ee-7a1b-473f-88df-36bfa8d65a3b";
        public static Guid EditorFactory = new Guid(EditorFactoryString);

        public const string VSIXLinqPadForVSString = "3f1a46fd-be36-4a1c-a5f8-92f10bad882d";
        public static Guid VSIXLinqPadForVS = new Guid(VSIXLinqPadForVSString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int TWindowToolbar = 0x1000;
        public const int TWindowToolbarGroup = 0x1050;
        public const int DisplayLinqPadStatementsResults = 0x0111;
        public const int DisplayLinqPadMethodResults = 0x0112;
        public const int EditorLinqPad = 0x0114;
        public const int EditorGroup = 0x0001;
    }
}